CREATE TABLE `corporate_actions` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`action_type` enum('dividend','split','reverse_split','merger','acquisition','spinoff','delisting','rights_issue','bonus_issue','buyback','name_change','ticker_change','hard_fork','airdrop','token_burn','staking_reward','appraisal_update','ownership_transfer','restoration','recertification') NOT NULL,
	`announcement_date` date NOT NULL,
	`effective_date` date NOT NULL,
	`record_date` date,
	`payment_date` date,
	`details` json,
	`status` enum('announced','confirmed','completed','cancelled') NOT NULL DEFAULT 'announced',
	`impact_on_holdings` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `corporate_actions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `counterparties` (
	`id` varchar(64) NOT NULL,
	`name` varchar(255) NOT NULL,
	`legal_name` varchar(255),
	`lei` varchar(20),
	`entity_type` enum('bank','broker_dealer','exchange','custodian','clearing_house','hedge_fund','private_equity','insurance_company','corporate','government','individual') NOT NULL,
	`country` varchar(2),
	`credit_rating` varchar(10),
	`rating_agency` varchar(50),
	`risk_level` enum('low','medium','high','critical') DEFAULT 'medium',
	`is_regulated` boolean DEFAULT true,
	`regulators` json,
	`exposure_limit` decimal(20,2),
	`current_exposure` decimal(20,2),
	`collateral_required` boolean DEFAULT false,
	`status` enum('active','suspended','defaulted','inactive') NOT NULL DEFAULT 'active',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `counterparties_id` PRIMARY KEY(`id`),
	CONSTRAINT `counterparties_lei_unique` UNIQUE(`lei`)
);
--> statement-breakpoint
CREATE TABLE `price_history` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`date` date NOT NULL,
	`open` decimal(20,8),
	`high` decimal(20,8),
	`low` decimal(20,8),
	`close` decimal(20,8) NOT NULL,
	`volume` bigint,
	`adj_close` decimal(20,8),
	`market_cap` decimal(20,2),
	`source` varchar(50) NOT NULL DEFAULT 'yahoo-finance',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `price_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `securities` (
	`id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`name` text NOT NULL,
	`asset_class` enum('equity','etf','bond','reit','mutual_fund','option','future','swap','structured_product','crypto','stablecoin','nft','tokenized_asset','artwork','collectible','wine','real_estate','private_equity','venture_capital','hedge_fund','commodity','forex','other') NOT NULL,
	`market_type` enum('exchange_traded','otc','private','decentralized','physical') NOT NULL,
	`exchange` varchar(100),
	`trading_venue` varchar(100),
	`currency` varchar(10) NOT NULL DEFAULT 'AUD',
	`denomination` varchar(50),
	`isin` varchar(12),
	`sedol` varchar(7),
	`cusip` varchar(9),
	`figi` varchar(12),
	`lei` varchar(20),
	`contract_address` varchar(100),
	`blockchain` varchar(50),
	`token_standard` varchar(20),
	`registry_id` varchar(100),
	`certificate_number` varchar(100),
	`appraisal_id` varchar(100),
	`sector` varchar(100),
	`industry` varchar(100),
	`country` varchar(2),
	`region` varchar(100),
	`metadata` json,
	`last_price` decimal(20,8),
	`last_price_date` timestamp,
	`last_volume` bigint,
	`market_cap` decimal(20,2),
	`is_liquid` boolean DEFAULT true,
	`min_trade_size` decimal(20,8),
	`lot_size` decimal(20,8),
	`listing_date` date,
	`delisting_date` date,
	`maturity_date` date,
	`is_active` boolean NOT NULL DEFAULT true,
	`status` enum('active','suspended','delisted','matured','defaulted','sold') NOT NULL DEFAULT 'active',
	`parquet_url` text,
	`data_product_id` varchar(64),
	`external_data_sources` json,
	`regulatory_classification` varchar(100),
	`is_regulated` boolean DEFAULT true,
	`custodian` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`created_by` varchar(64),
	`source` varchar(50) NOT NULL DEFAULT 'manual',
	`verification_status` enum('unverified','pending','verified','disputed') NOT NULL DEFAULT 'unverified',
	`verified_by` varchar(64),
	`verified_at` timestamp,
	CONSTRAINT `securities_id` PRIMARY KEY(`id`),
	CONSTRAINT `securities_isin_unique` UNIQUE(`isin`),
	CONSTRAINT `securities_sedol_unique` UNIQUE(`sedol`),
	CONSTRAINT `securities_cusip_unique` UNIQUE(`cusip`),
	CONSTRAINT `securities_figi_unique` UNIQUE(`figi`),
	CONSTRAINT `securities_lei_unique` UNIQUE(`lei`)
);
--> statement-breakpoint
CREATE TABLE `security_esg_ratings` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`rating_date` date NOT NULL,
	`environmental_score` decimal(5,2),
	`social_score` decimal(5,2),
	`governance_score` decimal(5,2),
	`overall_esg_score` decimal(5,2),
	`esg_rating` varchar(10),
	`rating_provider` varchar(100),
	`carbon_intensity` decimal(15,4),
	`carbon_footprint` decimal(20,2),
	`climate_risk` enum('low','medium','high','severe'),
	`controversy_level` enum('none','low','moderate','high','severe'),
	`controversy_details` text,
	`sdg_alignment` json,
	`impact_metrics` json,
	`source` varchar(100),
	`data_quality` enum('low','medium','high') DEFAULT 'medium',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_esg_ratings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_events` (
	`id` varchar(64) NOT NULL,
	`event_type` varchar(50) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50),
	`event_data` json NOT NULL,
	`source` varchar(50) NOT NULL,
	`user_id` varchar(64),
	`timestamp` timestamp NOT NULL,
	`kafka_offset` bigint,
	`kafka_partition` int,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `security_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_insurance` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50),
	`policy_number` varchar(100) NOT NULL,
	`insurer` varchar(255) NOT NULL,
	`insurance_type` enum('property','fine_art','collectibles','transit','storage','cyber','title','credit_default') NOT NULL,
	`coverage_amount` decimal(20,2) NOT NULL,
	`currency` varchar(10) NOT NULL,
	`deductible` decimal(20,2),
	`premium` decimal(20,2),
	`premium_frequency` enum('monthly','quarterly','annual'),
	`effective_date` date NOT NULL,
	`expiry_date` date NOT NULL,
	`policy_document` text,
	`status` enum('active','expired','cancelled','claimed') NOT NULL DEFAULT 'active',
	`claim_history` json,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_insurance_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_lending` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`lending_type` enum('securities_lending','crypto_staking','crypto_lending','collateral','repo') NOT NULL,
	`lender` varchar(255),
	`borrower` varchar(255),
	`platform` varchar(255),
	`quantity` decimal(20,8) NOT NULL,
	`collateral_value` decimal(20,2),
	`interest_rate` decimal(8,4),
	`staking_reward_rate` decimal(8,4),
	`start_date` date NOT NULL,
	`end_date` date,
	`lockup_period` int,
	`status` enum('active','completed','defaulted','recalled') NOT NULL DEFAULT 'active',
	`rewards_earned` decimal(20,8),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_lending_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_locations` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50),
	`location_type` enum('vault','gallery','warehouse','cold_storage','hot_wallet','custodian','exchange','property','cellar','safe_deposit_box','personal_residence') NOT NULL,
	`facility_name` varchar(255),
	`address` text,
	`city` varchar(100),
	`country` varchar(2),
	`coordinates` varchar(50),
	`custodian` varchar(255),
	`custodian_contact` varchar(255),
	`wallet_address` varchar(255),
	`wallet_type` varchar(50),
	`security_measures` json,
	`access_restrictions` text,
	`environmental_conditions` json,
	`last_verified` timestamp,
	`verified_by` varchar(64),
	`status` enum('active','in_transit','relocated','disposed') NOT NULL DEFAULT 'active',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_locations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_ownership` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`portfolio_id` varchar(64),
	`owner_id` varchar(64) NOT NULL,
	`owner_name` varchar(255),
	`ownership_type` enum('full','fractional','beneficial','nominee','syndicate','trust') NOT NULL,
	`ownership_percentage` decimal(10,6),
	`units` decimal(20,8),
	`acquisition_date` date NOT NULL,
	`acquisition_price` decimal(20,8),
	`acquisition_currency` varchar(10),
	`syndication_agreement` text,
	`co_owners` json,
	`voting_rights` boolean DEFAULT true,
	`transfer_restrictions` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_ownership_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_relationships` (
	`id` varchar(64) NOT NULL,
	`parent_security_id` varchar(64) NOT NULL,
	`child_security_id` varchar(64) NOT NULL,
	`relationship_type` enum('stock_split','reverse_split','merger','spinoff','conversion','underlying','etf_holding','index_component','adr_ordinary','preferred_common','warrant_stock','option_stock','token_asset') NOT NULL,
	`relationship_ratio` varchar(50),
	`effective_date` date NOT NULL,
	`end_date` date,
	`conversion_price` decimal(20,8),
	`details` json,
	`status` enum('active','completed','cancelled') NOT NULL DEFAULT 'active',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_relationships_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `security_restrictions` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`ticker` varchar(50),
	`restriction_type` enum('lockup','vesting','transfer_restriction','trading_restriction','regulatory','contractual','blackout','insider_trading') NOT NULL,
	`start_date` date NOT NULL,
	`end_date` date,
	`vesting_schedule` json,
	`percentage_restricted` decimal(5,2),
	`quantity_restricted` decimal(20,8),
	`reason` text,
	`legal_document` text,
	`can_sell` boolean DEFAULT false,
	`can_transfer` boolean DEFAULT false,
	`can_pledge` boolean DEFAULT false,
	`penalty_for_violation` text,
	`status` enum('active','expired','waived','violated') NOT NULL DEFAULT 'active',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `security_restrictions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `tax_lots` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`portfolio_id` varchar(64) NOT NULL,
	`ticker` varchar(50) NOT NULL,
	`acquisition_date` date NOT NULL,
	`quantity` decimal(20,8) NOT NULL,
	`cost_basis` decimal(20,8) NOT NULL,
	`total_cost` decimal(20,2) NOT NULL,
	`currency` varchar(10) NOT NULL,
	`acquisition_method` enum('purchase','gift','inheritance','airdrop','staking_reward','dividend_reinvestment','stock_split','merger','conversion') NOT NULL,
	`tax_treatment` enum('short_term','long_term','tax_deferred','tax_exempt','capital_gains','ordinary_income'),
	`disposal_date` date,
	`disposal_price` decimal(20,8),
	`disposal_method` enum('sale','gift','donation','loss','transfer'),
	`realized_gain_loss` decimal(20,2),
	`is_wash_sale` boolean DEFAULT false,
	`status` enum('open','closed','transferred') NOT NULL DEFAULT 'open',
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tax_lots_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `valuations` (
	`id` varchar(64) NOT NULL,
	`security_id` varchar(64) NOT NULL,
	`valuation_date` date NOT NULL,
	`valuation_amount` decimal(20,2) NOT NULL,
	`currency` varchar(10) NOT NULL,
	`valuation_type` enum('market','appraisal','insurance','liquidation','replacement','fair_value') NOT NULL,
	`appraiser` varchar(255),
	`appraisal_document` text,
	`methodology` text,
	`notes` text,
	`confidence` enum('low','medium','high') DEFAULT 'medium',
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`created_by` varchar(64),
	CONSTRAINT `valuations_id` PRIMARY KEY(`id`)
);
